name: exome
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp=0.19.5
  - bwa=0.7.17
  - samtools=1.9
  - gatk4=4.1.3.0
  - bcftools=1.9
  - snpeff=4.3.1t
  - fire=0.2.1
  - pandas=0.25.1
